# Default config for TIOT clinents
default_config:

homeassistant:
  packages: !include_dir_named packages/
  
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml
climate: !include climates.yaml
# End default config for TIOT clients
