################################################################################
#
# Sample lovelace card to display all data from packages
#
# type: vertical-stack
# cards:
#   - type: markdown
#     content: '## __Server__'
#   - type: glance
#     entities:
#       - entity: sensor.processor_temperature
#         name: CPU
#       - entity: sensor.processor_use
#         name: CPU
#       - entity: sensor.load_15m
#         name: Load
#       - entity: sensor.memory_use_percent
#         name: RAM
#       - entity: sensor.swap_use_percent
#         name: Swap
#     columns: 5
#   - type: glance
#     entities:
#       - entity: sensor.time_online
#         name: Online
#       - entity: binary_sensor.rpi_power_status
#         name: Power
#       - entity: sensor.database_size
#         name: Database
#         icon: mdi:database
#       - entity: sensor.disk_use
#         name: Disk
#       - entity: sensor.disk_use_percent
#         name: Disk
#     columns: 5
#   - type: glance
#     entities:
#       - entity: sensor.unavailable_entities
#         name: Unavailable
#       - entity: sensor.updates_available
#         name: Updates
#       - entity: sensor.ha_newest_version
#         name: HA Newest
#   - type: entities
#     entities:
#       - entity: script.update_packages
#
################################################################################

homeassistant:
  # Two factor authentication
  auth_mfa_modules:
    - type: notify
      message: 'Codul de acces este: {}'
    - type: totp
      name: Authenticator app

recorder:
  # Set recorder to use MariaDB
  db_url: !secret recorder_db_url
  purge_keep_days: !secret recorder_keep_days
  exclude:
    entities:
      - automation.healthchecks
http:
  # Setup NGINX
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    
rest_command:
  # monitor server with healthchecks.io
  healthchecks:
    url: !secret healthchecks

#Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids: !secret telegram_allowed_chat_ids
notify:
  - platform: telegram
    name: tiot_telegram
    chat_id: !secret telegram_notify_chat_id

sensor:
    # RPI sensors
  - platform: systemmonitor
    resources:
     - type: processor_use
     - type: swap_use_percent
     - type: processor_temperature
     - type: load_15m
     - type: memory_use_percent
     - type: disk_use_percent
       arg: /
     - type: disk_use
       arg: /
  - platform: uptime
    name: Time Online

    # MariaDB database size
  - platform: sql
    db_url: !secret recorder_db_url
    queries:
      - name: "DataBase size"
        query: !secret recorder_db_query 
        column: "value"
        unit_of_measurement: MB   

automation:
    # Notify on server start using defined service
  - id: 'server_start'
    alias: Server Start
    description: ''
    trigger:
    - platform: homeassistant
      event: start
    condition: []
    action:
    - service: !secret notify_service
      data:
        message: 🦾 Serverul a pornit!
    mode: single
    
    # Ping healthchecks.io every minute
  - id: 'healthchecks_update'
    alias: HealthChecks
    description: ''
    trigger:
      - platform: time_pattern
        minutes: /1
    condition: []
    action:
      - service: rest_command.healthchecks
    mode: single
