sensor:
### monitorizare server rpi
  - platform: systemmonitor
    resources:
     - type: processor_use
     - type: swap_use_percent
     - type: processor_temperature
     - type: load_15m
     - type: memory_use_percent
     - type: disk_use_percent
       arg: /
     - type: disk_use
       arg: /
     - type: load_15m
  - platform: uptime
    name: Time Online


### size of MariaDB
### https: //www.home-assistant.io/components/sensor.sql/
  - platform: sql
    db_url: !secret db_url
    queries:
      - name: 'DataBase size'
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length)  /1024/1024) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: MB   
        
### monitorizare server healthchecks.io
rest_command:
  healthchecks:
    url: !secret healthchecks

### Two factor autentification
homeassistant:
  auth_mfa_modules:
    - type: notify
      message: 'Codul de acces este: {}'
    - type: totp
      name: Authenticator app

recorder:
  db_url: !secret db_url
  purge_keep_days: !secret recorder_keep_days
  exclude:
    entities:
      - automation.healthcheck

### http settings pt ngnx
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

automation:
  - id: 'server_start'
    alias: Server Start
    description: ''
    trigger:
    - platform: homeassistant
      event: start
    condition: []
    action:
    - service: !secret notify_service
      data:
        message: 🦾 Serverul a pornit!
    mode: single
    
  - id: 'healthcheck_update'
    alias: HealthChecks
    description: ''
    trigger:
      - platform: time_pattern
        minutes: /1
    condition: []
    action:
      - service: rest_command.healthchecks
    mode: single

