# Package - Unavailable Entities Sensor
# Count and list of entities with a state of unavailable
#
# You must set in secrets.yaml
# delay_notify_unavailable: 00:10:00
# notify_service_unavailable: notify.notify
# 
# If you want to exlcude entities create group ignored_unavailable in groups.yaml
#
# Example:
#  ignored_unavailable:
#    entities:
#       - sensor.temperature

script:
  # Script to update this package from GitHub
  update_packages:
    sequence:
      - service: downloader.download_file
        data:
          overwrite: true
          url: >-
            https://raw.githubusercontent.com/topaniot/HomeAssistant_Packages/main/packages/unavailable_entities.yaml

group:
  ignored_unavailable:
    name: Ingnored Unavailable Devices
    entities: []

template:
  - sensor:
      - name: "Unavailable Entities"
        icon: "mdi:format-list-checks"
        state: >
              {{ states
                |selectattr('state','in',['unavailable','unknown','none'])
                |rejectattr('domain','in',['group','person','device_tracker','media_player'])
                |rejectattr('entity_id','search','_rssi')
                |rejectattr('entity_id','search','_ssid')
                |rejectattr('entity_id','search','_ip')
                |rejectattr('entity_id','search','_firmware_update')
                |rejectattr('entity_id','search','_wi_fi')
                |rejectattr('entity_id','search','_overheating')
                |rejectattr('entity_id','search','_overpowering')
                |rejectattr('entity_id','search','_ds18b20_')
                |rejectattr('entity_id','search','_htu21_')
                |rejectattr('entity_id','search','_energy')
                |rejectattr('entity_id','search','_power')
                |rejectattr('entity_id','search','_input')
                |rejectattr('entity_id','search','_device_temperature')
                |rejectattr('entity_id','search','_analog_temperature')
                |rejectattr('entity_id','in',state_attr('group.ignored_unavailable','entity_id'))
                |list|count
              }}
        attributes:
            names: >
              {{ states
                |selectattr('state','in',['unavailable','unknown','none'])
                |rejectattr('domain','in',['group','person','device_tracker','media_player'])
                |rejectattr('entity_id','search','_rssi')
                |rejectattr('entity_id','search','_ssid')
                |rejectattr('entity_id','search','_ip')
                |rejectattr('entity_id','search','_firmware_update')
                |rejectattr('entity_id','search','_wi_fi')
                |rejectattr('entity_id','search','_overheating')
                |rejectattr('entity_id','search','_overpowering')
                |rejectattr('entity_id','search','_ds18b20_')
                |rejectattr('entity_id','search','_htu21_')
                |rejectattr('entity_id','search','_energy')
                |rejectattr('entity_id','search','_power')
                |rejectattr('entity_id','search','_input')
                |rejectattr('entity_id','search','_device_temperature')
                |rejectattr('entity_id','search','_analog_temperature')
                |rejectattr('entity_id','in',state_attr('group.ignored_unavailable','entity_id'))
                |map(attribute='name')|join(', ')
              }}

input_boolean:
  unavailable_entities_alert:
    name: Unavailable Entities Alert
    icon: "mdi:alert-circle"

automation:
  - id: "unavailable_entities"
    alias: Unavailable Entities
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.unavailable_entities
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.unavailable_entities
                state: unknown
            sequence: []
          - conditions:
              - condition: numeric_state
                entity_id: sensor.unavailable_entities
                above: '0'
                below: '2'
            sequence:
              - delay: !secret delay_notify_unavailable
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.unavailable_entities_alert
              - service: !secret notify_service_unavailable
                data:
                  message: |
                    🔴 Este un dispozitiv indisponibil:
                    – {{ state_attr('sensor.unavailable_entities','names').split(',') | join('
                    –') }}
          - conditions:
              - condition: numeric_state
                entity_id: sensor.unavailable_entities
                above: '1'
            sequence:
              - delay: !secret delay_notify_unavailable
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.unavailable_entities_alert
              - service: !secret notify_service_unavailable
                data:
                  message: |
                    🔴 Sunt {{ states('sensor.unavailable_entities')|int }} dispozitive indisponibile:
                    – {{ state_attr('sensor.unavailable_entities','names').split(',') | join('
                    –') }}
          - conditions:
              - condition: numeric_state
                entity_id: sensor.unavailable_entities
                below: '1'
              - condition: state
                entity_id: input_boolean.unavailable_entities_alert
                state: 'on'
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.unavailable_entities_alert
              - service: !secret notify_service_unavailable
                data:
                  message: "🟢 Toate dispozitivele funcționzează!"
        default: []