# Package - Updates Available
# List all available updates of entities with device class update
#
# You must set in secrets.yaml
# notify_service_updates: "notify.notify"
# delay_notify_updates: "24:00:00"
#
# If you want to exlcude entities create group ignored_updates in groups.yaml
#
# Example:
# ignored_updates:
#   entities:
#     - binary_sensor.updater

script:
  # Script to update this package from GitHub
  update_packages:
    sequence:
      - service: downloader.download_file
        data:
          overwrite: true
          url: >-
            https://raw.githubusercontent.com/topaniot/HomeAssistant_Packages/main/packages/updates_available.yaml

group:
  ignored_updates:
    name: Ignored Updates
    entities:
      - binary_sensor.updater

sensor:
  - platform: version

template:
  - trigger:
      - platform: time_pattern
        minutes: "/1"
    sensor:
      - name: "Updates Available"
        icon: "hass:update"
        state: >
              {{ states
                |selectattr('attributes.device_class','eq','update')
                |rejectattr('state', 'in', ['off','unknown','unavailable','none'])
                |rejectattr('entity_id','in',state_attr('group.ignored_updates','entity_id'))
                |list|count 
              }}
        attributes:
            names: >
              {{ states
                |selectattr('attributes.device_class','eq','update')
                |rejectattr('state', 'in', ['off','unknown','unavailable','none'])
                |rejectattr('entity_id','in',state_attr('group.ignored_updates','entity_id'))
                |map(attribute='name')|join (", ")
              }}
  - trigger:
      - platform: time_pattern
        minutes: "/1"          
    sensor:
      - name: "HA Newest Version"
        icon: "hass:package"
        state: >
          {% if state_attr('binary_sensor.updater', 'newest_version') != states('sensor.current_version') %}
            {{ state_attr('binary_sensor.updater', 'newest_version') }}
          {% else %}
            Up-to-date
          {% endif %}

input_boolean:
  updates_available_alert:
    name: Updates Available Alert
    icon: "mdi:alert-circle"
  update_available_ha_alert:
    name: Update Available HA Alert
    icon: "mdi:alert-circle"

automation:
  # Notify when updates are available
  - id: "updates_available"
    alias: Updates Available
    mode: restart
    trigger:
      - platform: state
        entity_id: sensor.updates_available
        for: "00:00:05"
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.updates_available
                state: unknown
            sequence: []
          - conditions:
              - condition: numeric_state
                entity_id: sensor.updates_available
                above: '0'
                below: '2'
            sequence:
              - delay: !secret delay_notify_updates
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.updates_available_alert
              - service: !secret notify_service_updates
                data:
                  message: |
                    🟡 Este o actualizare disponibilă:
                    – {{ state_attr('sensor.updates_available','names').split(',') | join('
                    –') }}
          - conditions:
              - condition: numeric_state
                entity_id: sensor.updates_available
                above: '1'
            sequence:
              - delay: !secret delay_notify_updates
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.updates_available_alert
              - service: !secret notify_service_updates
                data:
                  message: |
                    🟡 Sunt {{ states('sensor.updates_available')|int }} actualizări disponibile:
                    – {{ state_attr('sensor.updates_available','names').split(',') | join('
                    –') }}
          - conditions:
              - condition: numeric_state
                entity_id: sensor.updates_available
                below: '1'
              - condition: state
                entity_id: input_boolean.updates_available_alert
                state: 'on'
            sequence:
              - service: !secret notify_service_updates
                data:
                  message: "🎉 Dispozitivele sunt actualizate!"
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.updates_available_alert
        default: []

  # Notify when Home Assistant update is available
  - id: "update_available_ha"     
    alias: Update Available HA
    description: ''
    trigger:
      - platform: state
        entity_id: sensor.ha_newest_version
        for: "00:00:05"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sensor.unavailable_entities
                state: unknown
            sequence: []
          - conditions:
              - condition: state
                entity_id: sensor.ha_newest_version
                state: 'Up-to-date'
              - condition: state
                entity_id: input_boolean.update_available_ha_alert
                state: 'on'
            sequence:
              - service: !secret notify_service_updates
                data:
                  message: "🎉 Home Assistant este actualizat!"
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.update_available_ha_alert
          - conditions:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: sensor.ha_newest_version
                    state: 'Up-to-date'
            sequence:
              - delay: !secret delay_notify_updates
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.update_available_ha_alert
              - service: !secret notify_service_updates
                data:
                  message: |
                    🎉 HA {{ state_attr('binary_sensor.updater', 'newest_version') }} disponibil!
                    Actual {{ states('sensor.current_version') }}
                    
                    Note versiune:
                    {{ state_attr('binary_sensor.updater', 'release_notes') }}
        default: []
    mode: restart
